### ISSUE TITLE
.getPlaylist() still broken? Cannot read property 'split' of undefined.

### ISSUE THREAD

**Issue by NovaLynxie** [DevSnowflake/soundcloud-scraper#22]
Hey there, I need some help figuring this out.

I have been trying to use the soundcloud-scraper module to get playlist track data but keep running into a problem.
I can get individual songs just fine using getSongInfo() but using getPlaylist() fail and throws an error.
I expected a response like what is mentioned [here](https://github.com/DevSnowflake/soundcloud-scraper#playlist) in the readme but instead I get this error message:
![image](https://user-images.githubusercontent.com/21307676/136205582-91edf165-fabc-4173-93dc-0c2c76290ef1.png)
In this example, I was using this [playlist](https://soundcloud.com/cg5-beats/sets/patiently-new-album) as the source.

This is the code used to test this out:
```js
const SoundCloud = require("soundcloud-scraper");
const client = new SoundCloud.Client();
let playlist;
(async function () {
  playlist = await client.getPlaylist("https://soundcloud.com/cg5-beats/sets/patiently-new-album");
  console.log(playlist);
})();
```

Version Information
Node v14.17.1
soundcloud-scraper v5.0.2

Can anyone help me and or provide fixes to resolve this?

Issue may be identical to #19 though not sure if they're using the same version.

**Comment by NovaLynxie** [comment]
Ok, after rolling back to v4.0.1 the aformentioned method works again.
It seems after version 5.0.0 getPlaylist() method stops working entirely.

**Comment by maskalix** [comment]
Found out solution!

Change in Client.js in section getPlaylist
this:
```
try {
                    section = JSON.parse(`[{"id": ${raw.split(`{}})},[{"id":`)[1].split(");")[0]}`);
                } catch(e) {
                    throw new Error(`Could not parse playlist:\n${e.message}`);
                }

                const data = Util.last(section).data[0];
```
To this:
```
try {
                section = JSON.parse(`{"hydratable":"playlist" ${raw.split(`},{"hydratable":"playlist"`)[1].split(`"}}];`)[0] + `"}}`}`);
            } catch(e) {
                throw new Error(`Could not parse playlist:\n${e.message}`);
            }
            const data = section.data;
```

Then it works normally as before ;)

**Comment by Ruzie** [comment]
> Found out solution!
> 
> Change in Client.js in section getPlaylist this:
> 
> ```
> try {
>                     section = JSON.parse(`[{"id": ${raw.split(`{}})},[{"id":`)[1].split(");")[0]}`);
>                 } catch(e) {
>                     throw new Error(`Could not parse playlist:\n${e.message}`);
>                 }
> 
>                 const data = Util.last(section).data[0];
> ```
> 
> To this:
> 
> ```
> try {
>                 section = JSON.parse(`{"hydratable":"playlist" ${raw.split(`},{"hydratable":"playlist"`)[1].split(`"}}];`)[0] + `"}}`}`);
>             } catch(e) {
>                 throw new Error(`Could not parse playlist:\n${e.message}`);
>             }
>             const data = section.data;
> ```
> 
> Then it works normally as before ;)

Great! But did you lint it correctly? Compared to current code, it looks like need to be linted, besides all good!

**Comment by maskalix** [comment]
> Great! But did you lint it correctly? Compared to current code, it looks like need to be linted, besides all good! 

My edit is in **pull requests**
